- name: Installation
  hosts: all  
  connection: local
  
  vars:
    mongo_src:
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-debian71-v3.4-latest.tgz
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-suse11-v3.4-latest.tgz
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel70-v3.4-latest.tgz
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-debian71-v3.2-latest.tgz
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-suse11-v3.2-latest.tgz
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel70-v3.2-latest.tgz
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-debian71-v3.0-latest.tgz
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-suse11-v3.0-latest.tgz
    - http://downloads.mongodb.org/linux/mongodb-linux-x86_64-rhel70-v3.0-latest.tgz
    mongodb_version: '3.4'  
    os_release: '70'    
 
  tasks:
  - debug: msg={{mongo_src | get_mongo_src(ansible_os_family, os_release, mongodb_version)}}
